version: 2.1
executors:
  java-8:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
commands:
  restore_workspace:
    steps:
      - attach_workspace:
          at: .
  gradle_cache:
    description: "Restore gradle caches"
    steps:
      - restore_cache:
          keys:
            - v1-gradlew-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradlew-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
jobs:
  checkout:
    executor: java-8
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew assemble
      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - lib/build
            - plugin/build
            - processor/build
  test:
    executor: java-8
    steps:
      - restore_workspace
      - gradle_cache
      - run: ./gradlew test
workflows:
  version: 2
  build-test:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - test:
          requires:
            - build
